import type { Database } from "./model";
export function createSeed(): Database {
  const now = new Date().toISOString();
  const year = new Date().getFullYear() + 1;
  const stamps = (id: string) => ({ id, createdAt: now, updatedAt: now });
  return {
    events: [
      {
        ...stamps("edc"),
        name: "EDC Colombia",
        startDate: `${year}-02-20`,
        endDate: `${year}-02-21`,
        city: "Bogotá",
        venue: "Parque Simón Bolívar",
        image: "",
        active: true,
      },
      {
        ...stamps("luna"),
        name: "Luna Eléctrica",
        startDate: `${year}-03-12`,
        endDate: "",
        city: "Medellín",
        venue: "La Macarena",
        image: "",
        active: true,
      },
      {
        ...stamps("aurora"),
        name: "Aurora en vivo",
        startDate: `${year}-04-09`,
        endDate: "",
        city: "Bogotá",
        venue: "Movistar Arena",
        image: "",
        active: true,
      },
    ],
    localities: [
      { id: "edc-general", eventId: "edc", name: "General · 2 días", order: 0 },
      { id: "edc-vip", eventId: "edc", name: "VIP · 2 días", order: 1 },
      { id: "luna-general", eventId: "luna", name: "General", order: 0 },
      { id: "luna-vip", eventId: "luna", name: "VIP", order: 1 },
      { id: "aurora-platea", eventId: "aurora", name: "Platea", order: 0 },
      {
        id: "aurora-preferencial",
        eventId: "aurora",
        name: "Preferencial",
        order: 1,
      },
    ],
    lots: [
      {
        ...stamps("maria"),
        eventId: "edc",
        localityId: "edc-general",
        owner: "María (demo)",
        phone: "",
        quantity: 3,
        cost: 400000,
        markup: 12.5,
        price: 450000,
        notes: "Datos ficticios de demostración.",
        active: true,
      },
      {
        ...stamps("enrique"),
        eventId: "edc",
        localityId: "edc-general",
        owner: "Enrique (demo)",
        phone: "",
        quantity: 2,
        cost: 430000,
        markup: 12,
        price: 480000,
        notes: "",
        active: true,
      },
      {
        ...stamps("jose"),
        eventId: "edc",
        localityId: "edc-vip",
        owner: "José (demo)",
        phone: "",
        quantity: 3,
        cost: 700000,
        markup: 12,
        price: 780000,
        notes: "",
        active: true,
      },
      {
        ...stamps("luna1"),
        eventId: "luna",
        localityId: "luna-general",
        owner: "Laura (demo)",
        phone: "",
        quantity: 4,
        cost: 180000,
        markup: 15,
        price: 207000,
        notes: "",
        active: true,
      },
      {
        ...stamps("luna2"),
        eventId: "luna",
        localityId: "luna-vip",
        owner: "Felipe (demo)",
        phone: "",
        quantity: 2,
        cost: 300000,
        markup: 15,
        price: 345000,
        notes: "",
        active: true,
      },
      {
        ...stamps("aurora1"),
        eventId: "aurora",
        localityId: "aurora-platea",
        owner: "Camila (demo)",
        phone: "",
        quantity: 3,
        cost: 260000,
        markup: 15,
        price: 299000,
        notes: "",
        active: true,
      },
      {
        ...stamps("aurora2"),
        eventId: "aurora",
        localityId: "aurora-preferencial",
        owner: "David (demo)",
        phone: "",
        quantity: 2,
        cost: 150000,
        markup: 20,
        price: 180000,
        notes: "",
        active: true,
      },
      {
        ...stamps("inactive"),
        eventId: "edc",
        localityId: "edc-general",
        owner: "Inventario propio (demo)",
        phone: "",
        quantity: 2,
        cost: 300000,
        markup: 10,
        price: 330000,
        notes: "Oculto mientras se confirma disponibilidad.",
        active: false,
      },
    ],
    reservations: [
      {
        ...stamps("reserved-demo"),
        lotId: "maria",
        quantity: 1,
        note: "Santiago · esperando transferencia de la entrada",
        status: "reserved",
        unitPrice: 450000,
        unitCost: 400000,
      },
      {
        ...stamps("sold-demo"),
        lotId: "jose",
        quantity: 1,
        note: "Venta de ejemplo completada",
        status: "completed",
        unitPrice: 780000,
        unitCost: 700000,
      },
    ],
    settings: {
      brand: "Andrés Le Vende",
      phone: "",
      markup: 15,
      buyerTemplate:
        "Hola, Andrés. Estoy interesado en una boleta para {evento}, localidad {localidad}. Vi que hay disponibilidad desde {precio}. ¿Qué opciones tienes?",
      sellerTemplate:
        "Hola, {propietario}. Tengo un comprador para {cantidad} boleta(s) de {evento}, localidad {localidad}. ¿Las tienes disponibles para continuar con la transferencia?",
    },
  };
}
